### ISSUE TITLE
AttributeError: 'Image' object has no attribute 'pixel_width'

### ISSUE THREAD

**Issue by Ankit-Misra** [barnabygordon/remote-sensing#5] opened 2020-07-11 13:44 UTC
Hi, I really liked your repository and wanted to try it out, but I'm getting this.
![error-remotesending](https://user-images.githubusercontent.com/38560700/87225446-acd94c00-c3aa-11ea-9366-e82f6af3351f.PNG)

**Comment by barnabygordon** [comment] 2020-07-11 14:52
@Ankit-Misra thank you for trying this repository out. I'll help you as best I can, but please bear in mind that this is still very much WIP.

I'm not able to reproduce your error, and I'm unsure why `pixel_to_world` is being called since there should be no dependancy on that within `bcet`.

Generally I don't construct `Image` from it's `__init__` but rather from the `Loader` class.

Here's is an example of how I typically use bcet:

```
from remotesensing.image import Loader
from remotesensing.processing import enhance

import matplotlib.pyplot as plt

image = Loader().load('image.tif')  # an image with multiple bands

bcet = enhance.bcet(image)  # bcet assumes the image value range is (0, 1), this can be overridden if using uint8 data

plt.imshow(bcet.pixels)  # bcet returns an Image object, so we need to use imshow on the image pixels
```

I plan to add some Jupyter notebooks to this repo with examples of how the classes are intended to be used.

**Comment by Ankit-Misra** [comment] 2020-07-15 20:12
Thanks for your help. I think a jupyter notebook will be great. Can you
please also give an example code of running SFIM for an input image?

**Comment by barnabygordon** [comment] 2020-07-16 20:02
@Ankit-Misra I've added a few examples of how I intend this project to be used. [See here for an example of SFIM](https://github.com/barnabygordon/remote-sensing/blob/master/examples/02_processing.ipynb).

I'll close this issue now since your original problem should be resolved now with these examples. Although, if you have any other problems or suggestions please don't hesitate to open another issue!

**Closed as completed by barnabygordon** 2020-07-16 20:02 UTC
